### ISSUE TITLE
upload to Melpa? 

### ISSUE THREAD

**Issue by yitang** [AnselmC/le-thesaurus.el#1]
found this package useful. is there a plan to move to Melpa?

**Comment by AnselmC** [comment]
Hey, that's nice to hear.

No active plans, but I'll look into it. If you've done this before, I'm glad about any help you can give

**Comment by yitang** [comment]
I started the uploading process in this PR - can you have a quick read on the licence and other checklist? 

https://github.com/melpa/melpa/pull/7992

**Comment by AnselmC** [comment]
So I fixed the linting issues (`package-lint` + `flycheck`). `checkdoc` is also ok.
Could you test your recipe?

When I have time I'll try to add some tests as well.

**Comment by AnselmC** [comment]
Hey @yitang, the biggest issue seems to be the package name.
I came up with some ideas (in no particular order):
- le thesaurus
- thethesaurus
- emacsaurus
- thesaurel
- the-saurus
- words.el (if this package should support dictionary.com lookups or something along those lines)

Any thoughts on these? Any other ideas?

**Comment by yitang** [comment]
hmm. to be honest, I don't really have a preference... just let me know so I will update the PR. :)

**Comment by AnselmC** [comment]
Alright, package has been renamed. License file is also there. The other mentioned issues have also been fixed.

**Comment by yitang** [comment]
great. I've updated the recipes and the PR. all looks good. let's see the review.

**Comment by AnselmC** [comment]
Worked out well. Thanks for the initiative!
