### ISSUE TITLE
Melpa homepage url is incorrect

### ISSUE THREAD

**Issue by hmelman** [AnselmC/le-thesaurus.el#19]
The entry for le-thesaurus on melpa is missing the `.el` for the homepage url.  I'm not sure how this is setup but you can see the issue in the Homepage butter on [this page](https://melpa.org/#/le-thesaurus)

**Comment by AnselmC** [comment]
Ah true I missed that when @yitang created the recipe: https://github.com/melpa/melpa/pull/7992/commits/fea3cd6ed61e0936ee1566e72dab66539be87fcd

Not sure how easy it is to change this.

**Comment by yitang** [comment]
I'm not sure what causes the missing .el in the home page... the link in the PR (https://github.com/melpa/melpa/pull/7992) is correct.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/6054101/169202975-707e1a1b-fa07-40e8-9a54-f34018ed209b.png">

**Comment by AnselmC** [comment]
I guess the recipe would have to be
```elisp
(le-thesaurus.el
 :repo "AnselmC/le-thesaurus.el"
 :fetcher github)
```

**Comment by hmelman** [comment]
It is working now :)
